### PR TITLE
Center align front page text

### PR DESCRIPTION
**Pull request by lironmele**
Critical fix please merge as soon as possible.

### CODE REVIEW

**Comment by alon12131415** [comment]
How will this affect the performance of the page? I think the effects should be seriously considered before merging such a critical fix.

**Comment by lironmele** [comment]
> How will this affect the performance of the page? I think the effects should be seriously considered before merging such a critical fix.

You are definitely right.

@AmitMT Let's consider moving to [VueJS](https://github.com/facebook/react).
I see that they handle this much better than React.

**Comment by AmitMT** [comment]
~***```
console.log("This is not a bug, it is intended.");```***~

**Comment by AmitMT** [comment]
> 

fuck you

**Comment by alon12131415** [comment]
> > How will this affect the performance of the page? I think the effects should be seriously considered before merging such a critical fix.
> 
> You are definitely right.
> 
> @AmitMT Let's consider moving to [VueJS](https://github.com/facebook/react). I see that they handle this much better than React.

I think that coding this in any language that is higher than c (we might also consider c++ but then serious code reviews should be conducted before every commit to master) would not produce ideal performance. 

@AmitMT Please consider making this code actually good and optimized before deploying the server to production.

Regards, N1kasu.

**Comment by lironmele** [comment]
> > > How will this affect the performance of the page? I think the effects should be seriously considered before merging such a critical fix.
> > 
> > 
> > You are definitely right.
> > @AmitMT Let's consider moving to [VueJS](https://github.com/facebook/react). I see that they handle this much better than React.
> 
> I think that coding this in any language that is higher than c (we might also consider c++ but then serious code reviews should be conducted before every commit to master) would not produce ideal performance.
> 
> @AmitMT Please consider making this code actually good and optimized before deploying the server to production.
> 
> Regards, N1kasu.

Hi N1kasu,

C is full of bugs and unsafe.
Let's try to rustify this projcet and maybe it can go to the moon🚀

**Pull request closed without merging**
